### ISSUE TITLE
Talk about the support for bypassing the pre-signed transactions

### ISSUE THREAD

**Issue by darosior** [re-vault/practical-revault#21]

**Comment by darosior** [comment]
I was arguing for explicitly allowing it as it's possible and we should not hide it. However, i feel like this is a significant threat without an according in-house watchtower policy as:
- users will be like wtf.
- it significantly increases -i believe- the success probability of a physical attack, while we strive for reducing it.

**Comment by darosior** [comment]
Same here, i'd like to discuss it on Monday. If you can start thinking about it @JSwambo @kloaec @edouardparis .

**Comment by edouardparis** [comment]
After discussion I think we agree for: ACK support the feature, but make it clear it is not the `revault` way of doing things

**Comment by darosior** [comment]
Yeah:

- PSBT flow

- A new GUI tab "bypass" for the stakeholders

-------- Original Message --------

**Comment by JSwambo** [comment]
Ack! 

Users should be educated that bypass cannot be revoked, and the GUI should reinforce this message. Not having a bypass would be a regression from current custody operations capabilities (multi-sig wallets).

**Comment by darosior** [comment]
As it's going to be PSBT flow, no need to be spec'd here. Closing this.
