### ISSUE TITLE
Automated refill of the fee-bumping utxo pool with vault's funds

### ISSUE THREAD

**Issue by darosior** [re-vault/practical-revault#28]
I can already imagine the *really* poor UX of having user to refill their utxo pools in order to be able to operate.

Can we come up with a mechanism to automatically refill as we use the architecture ?

An obvious one would be **eg** (did not think much about it) appending a [pre-defined value]sats output for each participant to the unvault transaction. It drains a small part of funds out of it, and the created outputs being unencumbered by a timelock they could directly be used to revault the attempt. This means we can *account for them as well* so this could avoid the dread of "please refill your WT's utxo pool" as long as feerate does not go crazy.

The only alternatives i can see to automated fee utxo pool refill are "batching ceremonies" and "refill ceremonies", which, well, we certainly want to prevent as much as possible.

ref https://github.com/re-vault/practical-revault/issues/16

**Comment by kloaec** [comment]
Seems okay-ish, not super clean tho.
I suppose one could use the sync server to somewhat request to have a refill UTXO in a spend? (automagically I suppose, when fee wallet gets low)

**Comment by JSwambo** [comment]
I'd like to note our working assumption here:
- A busy mempool and high fee-rate can occur at any time and so watchtowers must *always* be prepared. This means actively maintaining their fee-bumping UTXO pool.

There are a few open questions here:
- What is a sufficient amount of funds per vault UTXO, and how should these be distributed in a the fee-bump UTXO pool?
- Is it necessary for each watchtower to maintain 100% collateral for the entire set of vault UTXO?
- Given the two mechanisms for re-filling a watchtowers fee-bump UTXO pool (through change outputs and through routine signing ceremonies), can this process be practical and automatic? 

Half-baked idea:
- What if we enable co-operation between watchtowers? So WT1 broadcasts an RBF fee-bump tx signed with ANYONECANPAY|ALL. The fee-rate spikes and invalidates it. WT2 notices this transaction in the mempool and bumps the fee again.

**Comment by darosior** [comment]
Closing this, not relevant anymore. See #16.
