### ISSUE TITLE
Repo(s) organisation

### ISSUE THREAD

**Issue by darosior** [re-vault/practical-revault#3]
I thought to go with one repo per entity:
- Wallet
- Watchtower
- Cosig server
- Sync server

The communication channel code will probably be part of another repo (not here).

**Comment by edouardparis** [comment]
revault-wallet will be a lib crate like https://github.com/MagicalBitcoin/magical-bitcoin-wallet
and revault-gui will use revault-wallet as a dependcy ?
I think it would be the cleanest way to do it in order to have a clean wallet implem without too much dependencies

**Comment by darosior** [comment]
I wanted to have `revaultd` and `revault-gui` talking to it via a socket, but now that we need Windows support... I need to give some more thoughts.

In any case yep, I think the core logic --`revault-whatever`-- would be in a lib.

**Comment by darosior** [comment]
We settled on this:
## libs
`revault_tx` => Bitcoin Script and transactions primitives
`revault_net` => Communication channels and practical-revault messages

## bins
`revaultd` => "wallet" daemon
`watchtowerd`, `sync_serverd`, `cosignerd` => servers daemons
