### ISSUE TITLE
Managers can access the emergency transactions from the sync server

### ISSUE THREAD

**Issue by kloaec** [re-vault/practical-revault#37]
PLZ IMPLEMENT SIRS

**Comment by darosior** [comment]
We certainly need to implement domain separation on the sync server now that fund managers are not always stakeholders anymore.

**Comment by darosior** [comment]
But then it's not untrusted anymore aaaargh

**Comment by darosior** [comment]
We need to encrypt the emergency transaction signatures with the stakeholder public keys.
