### ISSUE TITLE
Hide Emergency address instead of encrypting Emergency signatures

### ISSUE THREAD

**Issue by darosior** [re-vault/practical-revault#72]
Just realised that we could just not share the Emergency address -which we currently consider "internally public"- at all with the managers. This would allow to simplify the protocol further by removing the workarounded encryption of the emergency signatures, as we exchange raw signatures (in order to use them an attacker -best fit would be a manager- would need to know the Emergency transaction structure).  I think it is an equivalent protection in our case as:
- As soon as the emergency address is publicly known, the wallet is decomissioned (you cannot perform a DOS if a DOS is already being performed :p)
- The encryption keys are hot and, aside of the usual brittle OS ACL used for the key file, the Emergency Address could be treated almost as privately

Am i ovelooking something ? @JSwambo

**Comment by JSwambo** [comment]
How to determine the transaction given the signature(s) by compromising the operation? 
- An attacker who compromises a stakeholder's wallet or watchtower would know signatures and Emergency Tx structure, but this is already the case

Given the signature can an attacker determine the Emergency Tx "cryptographically"? I don't think so... 
the signature `(r,s)` is given by two equations:
- `r = x_1  mod n`, where `(x_1, y_1) = k * G` for per-message secret `k` and generator `G`. -> knowing `r` one can't compute `k` without solving ECDLP.
- `s = k^(-1) (z + r*d_A)`, where `z` is derived from `HASH(message)`, `r` is known but is blinded by the private key `d_A`. -> knowing `(r,s)` but not `k` one can't compute `z` nor `d_A`. If one somehow computed `z` then _still_ they would need to find the pre-image of the hash to determine the Emergency Tx.

What about given multiple signatures for the same message? 
- As long as the per-message secret `k` is chosen as a secure random number for each signature and that each signature is generated with a different private key, there should be no correlation between any `(r_1, s_1)` and `(r_2, s_2)`

> "I think it is an equivalent protection in our case"

I don't think it's equivalent, but both seem good enough to me.

> "As soon as the emergency address is publicly known, the wallet is decomissioned (you cannot perform a DOS if a DOS is already being performed)"

I agree if you mean: if the emergency scenario is triggered, then the address will become public. In which case it doesn't need to be a secret any more. 

> "The encryption keys are hot ..."

I thought we were going with using the ECDSA keys on the HM for encrypting the emergency sigs?

**Comment by darosior** [comment]
> How to determine the transaction given the signature(s) by compromising the operation?

You don't ? The signature is using a hash of the message, you can't deduce the message out of it.

> I don't think it's equivalent, but both seem good enough to me.

I don't either. As mentioned i believe in our specific case it is (as in "for v0 practical-revault, `Compromised Keys => Compromised Emergency Address` `Compromised Emergency Address => Compromised Keys`"). Still not terribly confident about it, but we need to weigh in all the pitfalls of using random crypto stuff around too.

> I thought we were going with using the ECDSA keys on the HM for encrypting the emergency sigs?

We [*are* not](https://github.com/re-vault/practical-revault/blob/master/messages.md#sig-1) using the HM for this...
